### ISSUE TITLE
Working!!!

### ISSUE THREAD

**Issue by Shizuka-minamoto** [parthkatiyar314/Discord-poketwo-autocatcher#1]
100% LEGIT and Working!
Nice Support by the owner in hosting the bot.

**Comment by parthkatiyar314** [comment]
How so

**Comment by RenaissanceAlt** [comment]
> How so

it has webhook in it and your bot doesn,t even works.

**Comment by parthkatiyar314** [comment]
> > How so
> 
> it has webhook in it and your bot doesn't even works.
> join my discord server and show me https://discord.gg/hfjsYPmqaM

Join mine and see
https://discord.gg/tjNJEbYZ

**Comment by parthkatiyar314** [comment]
So the issue the person had that he used the token directly in the script. Please use environment variables otherwise your token may get stolen by someone. The bot is working and it is not a token grabber

**Comment by Shizuka-minamoto** [comment]
yeah true, it was my fault to use token directly.
This guy is 100% Legit!!!

**Comment by parthkatiyar314** [comment]
Thanks for confirming!!!
